[package]
edition = "2021"
name = "bsa"
publish = false
version = "0.1.0"

[dependencies]
bstr = "1.7.0"
memmap2 = "0.9.0"
thiserror = "1.0.50"

[dev-dependencies]
anyhow = "1.0.75"
walkdir = "2.4.0"
