name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/deploy_docs.yml'
      - 'src/**'

permissions:
  contents: write

jobs:
  deploy_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo doc --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/target/doc/ba2/
